[workspace]
members = [
  "rust/assert_no_alloc",
  "rust/ibig",
  "rust/sword",
  "rust/sword_crypto",
  "rust/sword_guard",
  "rust/sword_macros",
  "rust/sword_pma",
  "rust/murmur3",
  "rust/murmur3/murmur3-sys",
]
